

describe('TS03 Directory', () => {
  it('TC001 Access Directory Menu', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
  })
  it('TC002 Search By Registered Employee Name', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-sheet').click()
    cy.get('.orangehrm-qr-code').should('have.exist').and('have.visible')
  })
  it('TC003 Search By Unregistered Employee Name', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Invalid')
  })
  it('TC004 Search By Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC005 Search By Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(5) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC006 Search By Registered Employee Name And Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC007 Search By Registered Employee Name And Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC008 Search By Unregistered Employee Name and Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Invalid')
  })
  it('TC009 Search By Unregistered Employee Name and Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Invalid')
  })
  it('TC010 Search By Job Title and Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC011 Search By Registered Employee Name, Job Title and Location', () => {
  cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC012 Search By Unregistered Employee Name, Job Title and Location', () => {
  cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Invalid')
  })
  it('TC013 Reset After Type Registered Employee Name', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC014 Reset After Select Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC015 Reset After Select Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC016 Reset After Type Registered Employee Name and Select Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC017 Reset After Type Registered Employee Name and Select Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC018 Reset After Type Unregistered Employee Name and Select Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC019 Reset After Type Unregistered Employee Name and Select Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC020 Reset After Select Job Title and Select Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC021 Reset After Type Registered Employee Name, Select Job Title and Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  it('TC022 Reset After Type Unregistered Employee Name, Select Job Title and Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--ghost').click()
    cy.get('input[placeholder="Type for hints..."]').should('have.value', '')
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').should('have.value', '')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').should('have.value', '')
  })
  
  it('TC023 Top Menu About Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get('.oxd-userdropdown-tab').click()
    cy.get(':nth-child(1) > .oxd-userdropdown-link').click()
    cy.get('.orangehrm-modal-header > .oxd-text').should('have.text', 'About')
   })
   it('TC024 Top Menu Support Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get('.oxd-userdropdown-tab').click()
    cy.get(':nth-child(2) > .oxd-userdropdown-link').click()
    cy.get('.orangehrm-sub-title').should('have.text', 'Customer Support')
    cy.url().should('include', 'support')
   })
   it('TC025 Top Menu Change Password Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get('.oxd-userdropdown-tab').click()
    cy.get(':nth-child(3) > .oxd-userdropdown-link').click()
    cy.get('.orangehrm-card-container > .oxd-text--h6').should('have.text', 'Update Password')
    cy.url().should('include', 'updatePassword')
   })
   it('TC026 Top Menu Logout Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get('.oxd-userdropdown-tab').click()
    cy.get(':nth-child(4) > .oxd-userdropdown-link').click()
    cy.get('.oxd-text.oxd-text--h5.orangehrm-login-title').should('have.text', 'Login')
    cy.url().should('include', 'login')
   })
   it('TC027 Main Menu Button Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get('button[role="none"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > aside:nth-child(1) > nav:nth-child(1) > div:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1) > span:nth-child(2)').should('not.be.visible')
    cy.get('button[role="none"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > aside:nth-child(1) > nav:nth-child(1) > div:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1) > span:nth-child(2)').should('be.visible')
   })
  it('TC028 Top Menu Help Button Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.url().should('eq', 'https://opensource-demo.orangehrmlive.com/web/index.php/directory/viewDirectory')
    cy.window().then((win) => {
    cy.stub(win, 'open').as('windowOpen')})
    cy.get('.oxd-topbar-body-nav-slot > .oxd-icon-button').click()
    cy.get('@windowOpen').should('have.been.called')
  })
  it('TC029 Toggle Button Function', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'viewDirectory')
    cy.get(':nth-child(3) > .oxd-icon-button').click()
    cy.get(':nth-child(1) > .oxd-input-group > .oxd-input-group__label-wrapper > .oxd-label').should('not.be.visible')
    cy.get(':nth-child(3) > .oxd-icon-button').click()
    cy.get(':nth-child(1) > .oxd-input-group > .oxd-input-group__label-wrapper > .oxd-label').should('be.visible')
  })
})
