import loginPage from "../../support/pagesOrangeHRM/loginPage"
import loginData from "../../fixtures/loginDataOrangeHRM/loginData.json"
const Login = loginPage
describe('TS01 Login', () => {
  it('TC001 Access Login Valid Username and Password', () => {
    Login.visit()
    Login.inputValidUsername(loginData.validUsername)   
    Login.inputValidPassword(loginData.validPassword)
    Login.interceptSubUnit()
    Login.clickLoginButton()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    Login.directToDashboard()
  })
  it('TC002 Access Login Invalid Username and Valid Password', () => {
    Login.visit()
    Login.inputInvalidUsername(loginData.invalidUsername)
    Login.inputValidPassword(loginData.validPassword)
    Login.interceptMessages()
    Login.clickLoginButton()
    cy.wait('@messages').its('response.statusCode').should('equal', 304)
    Login.getAlertInvalidCredentials()
    Login.stayAtLoginPage()
  })
  it('TC003 Access Login Valid Username and Invalid Password', () => {
    Login.visit()
    Login.inputValidUsername(loginData.validUsername)
    Login.inputInvalidPassword(loginData.invalidPassword)
    Login.interceptValidate()
    Login.clickLoginButton()
    cy.wait('@validate').its('response.statusCode').should('equal', 302)
    Login.getAlertInvalidCredentials()
    Login.stayAtLoginPage()
  })
  it('TC004 Access Login Invalid Username and Password', () => {
    Login.visit()
    Login.inputInvalidUsername(loginData.invalidUsername)
    Login.inputInvalidPassword(loginData.invalidPassword)
    Login.interceptValidate()
    Login.clickLoginButton()
    cy.wait('@validate').its('response.statusMessage').should('equal', 'Found')
    Login.getAlertInvalidCredentials()
    Login.stayAtLoginPage()
  })
  it('TC005 Access Login Valid Username and Blank Password', () => {
    Login.interceptLogin()
    Login.visit()
    Login.inputValidUsername(loginData.validUsername)
    Login.inputBlankPassword(loginData.blankPassword)
    Login.clickLoginButton()
    cy.wait('@login').should('include.all.keys', ['request', 'response'])
    Login.getAlertRequired()
    Login.stayAtLoginPage()
  })
  it('TC006 Access Login Blank Username and Valid Password', () => {
    Login.interceptLogin()
    Login.visit()
    Login.inputBlankUsername(loginData.blankUsername)
    Login.inputValidPassword(loginData.validPassword)
    Login.clickLoginButton()
    cy.wait('@login').its('response.statusCode').should('equal', 200)
    Login.getAlertRequired()
    Login.stayAtLoginPage()
  })
  it('TC007 Access Login Invalid Username and Blank Password', () => {
    Login.interceptLogin()
    Login.visit()
    Login.inputInvalidUsername(loginData.invalidUsername)
    Login.inputBlankPassword(loginData.blankPassword)
    Login.clickLoginButton()
    cy.wait('@login').its('response.statusMessage').should('equal', 'OK')
    Login.getAlertRequired()
    Login.stayAtLoginPage()
  })
  it('TC008 Access Login Blank Username and Invalid Password', () => {
    Login.interceptMessages()
    Login.visit()
    Login.inputBlankUsername(loginData.blankUsername)
    Login.inputInvalidPassword(loginData.invalidPassword)
    Login.clickLoginButton()  
    cy.wait('@messages').its('response.statusMessage').should('equal', 'OK')
    Login.getAlertRequired()
    Login.stayAtLoginPage()
  })
  it('TC009 Access Login Blank Username and Password', () => {
    Login.interceptMessages()
    Login.visit()
    Login.inputBlankUsername(loginData.blankUsername)
    Login.inputBlankPassword(loginData.blankPassword)
    Login.clickLoginButton()
    cy.wait('@messages').its('response.statusCode').should('equal', 200)
    Login.getAlertRequired()
    Login.stayAtLoginPage()
  })
  it('TC010 Forgot Password', () => {
    Login.visit()
    Login.interceptMessages()
    Login.clickForgotPasswordButton()
    cy.wait('@messages').its('response.statusMessage').should('equal', 'Not Modified')
    Login.directToResetCodePage()
  })
})