describe('TS01 Login', () => {
  it('TC001 Access Login Valid Username and Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.url().should('include', 'dashboard')
  })
  it('TC002 Access Login Invalid Username and Valid Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('dimas').should('not.have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-alert').should('contain', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
  it('TC003 Access Login Valid Username and Invalid Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('dimas456').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-alert').should('contain', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
  it('TC004 Access Login Invalid Username and Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('dimas').should('not.have.value', 'Admin')
    cy.get('[name="password"]').type('dimas123').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-alert').should('contain', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
  it('TC005 Access Login Valid Username and Blank Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Required')
    cy.url().should('include', 'login')
  })
  it('TC006 Access Login Blank Username and Valid Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').should('not.have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Required')
    cy.url().should('include', 'login')
  })
  it('TC007 Access Login Invalid Username and Blank Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Dimas').should('not.have.value', 'Admin')
    cy.get('[name="password"]').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Required')
    cy.url().should('include', 'login')
  })
  it('TC008 Access Login Blank Username and Invalid Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').should('not.have.value', 'Admin')
    cy.get('[name="password"]').type('dimas123').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Required')
    cy.url().should('include', 'login')
  })
  it('TC009 Access Login Blank Username and Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').should('not.have.value', 'Admin')
    cy.get('[name="password"]').should('not.have.value', 'admin123')
    cy.get('[type="submit"]').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Required')
    cy.url().should('include', 'login')
  })
  it('TC010 Forgot Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.orangehrm-login-forgot > .oxd-text').click()
    cy.url().should('include', 'ResetCode')
  })
})

