

describe('TS03 Directory', () => {
  it('TC001 Access Directory Menu', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
  })
  it('TC002 Sort By Unregistered Employee Name', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Dimas Novtel').should('have.value', 'Dimas Novtel')
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input-group > .oxd-text').should('contain', 'Invalid')
  })
  it('TC003 Sort By Registered Employee Name', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-sheet').click()
    cy.get('.orangehrm-qr-code').should('have.exist').and('have.visible')
  })
  it('TC004 Sort By Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(6) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC005 Sort By Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(5) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC006 Sort By Registered Employee Name And Job Title', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get('body > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').click()
    cy.get(':nth-child(5) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
  it('TC007 Sort By Registered Employee Name And Location', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin').should('have.value', 'Admin')
    cy.get('[name="password"]').type('admin123').should('have.value', 'admin123')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/subunit').as('subunit')
    cy.get('[type="submit"]').click()
    cy.wait('@subunit').its('response.statusCode').should('equal', 200)
    cy.url().should('include', 'dashboard')
    cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/directory/employees?limit=14&offset=0').as('employees')
    cy.get(':nth-child(9) > .oxd-main-menu-item').click()
    cy.wait('@employees').its('response.statusCode').should('equal', 200)
    cy.get('input[placeholder="Type for hints..."]').click()
    cy.get('input[placeholder="Type for hints..."]').type('Peter').should('have.value', 'Peter')
    cy.wait(4000)
    cy.get('[role="listbox"]').click()
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input').click()
    cy.get(':nth-child(4) > span').click()
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').should('have.exist').and('have.visible')
  })
})
